import Zeta2Lean.Window.Proofs.L20U.Pointwise
import Zeta2Lean.Window.Proofs.L20U.Numerics

set_option linter.style.header false
set_option linter.style.longLine false

/-!
# Theorem U, part 5a: certified numerical values for the landscape (GENERATED)

Generated by `gen_cert.py` (exact rational arithmetic; see the docstring of `L20U/Landscape.lean`).
Every `log`/`arctan` enclosure is re-checked here by `norm_num` through the lemmas of
`L20U/Numerics.lean` (`artanh` series with a geometric tail, alternating Taylor polynomials of
`arctan` with range reduction, `Real.log_two_gt_d9`/`_lt_d9`), and `π` by `Real.pi_gt_d20`,
`Real.pi_lt_d20`.  Values used (`p = 9`, true values in brackets):
* `C_η ≤ 255155223 / 200000` [`1275.7761127…`];
* `U(9) ≤ -(750631301 / 1000000)` [`-750.6313113…`];
* `7369 / 500000 ≤ U'(9) ≤ 14739 / 1000000` [`0.0147383…`];  hence `U(9) + 37 U'(9) ≤ -(375042979 / 500000) < -749`;
* cell `[46, 60]`: `5(arctan(159/46) + arctan(1/46)) - 23(arctan(93/60) - arctan(65/46)) - 2π ≤ -(44713 / 62500)`;
* tail: `5(arctan(159/60) + arctan(1/60)) - 2π ≤ -(150061 / 1000000)` [`-0.1503…`].
-/

open Real Finset

noncomputable section

namespace ZetaWindow

namespace L20U

/-- `U'(η)` for `η > 0` (`∂_η Gf(a, η) = arctan(a/η)`, `Gf(-1, ·) = -Gf(1, ·)`). -/
def dUw (η : ℝ) : ℝ :=
  5 * (Real.arctan (159 / η) + Real.arctan (1 / η)) -
    ∑ j ∈ Icc 1 23, (Real.arctan ((159 - (etaW j : ℝ)) / η) - Real.arctan (((etaW j : ℝ) - 1) / η)) -
      2 * π

theorem Gf_eq_pos {a y Q V : ℝ} (hQ : a ^ 2 + y ^ 2 = Q) (hV : a / y = V) :
    Gf a y = a / 2 * Real.log Q + y * Real.arctan V - a := by
  unfold Gf; rw [hQ, hV]

/-! ## Enclosures -/

theorem cl1 : Real.log (60 : ℝ) ≤ (255896535241 / 62500000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (60 : ℝ)) (z := (7 / 23 : ℝ)) (U := (255896535241 / 62500000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl2 : Real.log (58 : ℝ) ≤ (2030221505971 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (58 : ℝ)) (z := (13 / 45 : ℝ)) (U := (2030221505971 / 500000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl3 : Real.log (56 : ℝ) ≤ (4025351692017 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (56 : ℝ)) (z := (3 / 11 : ℝ)) (U := (4025351692017 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl4 : Real.log (54 : ℝ) ≤ (797796809559 / 200000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (54 : ℝ)) (z := (11 / 43 : ℝ)) (U := (797796809559 / 200000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl5 : Real.log (52 : ℝ) ≤ (246952732487 / 62500000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (52 : ℝ)) (z := (5 / 21 : ℝ)) (U := (246952732487 / 62500000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl6 : Real.log (50 : ℝ) ≤ (489002875829 / 125000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (50 : ℝ)) (z := (9 / 41 : ℝ)) (U := (489002875829 / 125000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl7 : Real.log (48 : ℝ) ≤ (3871201012109 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (48 : ℝ)) (z := (1 / 5 : ℝ)) (U := (3871201012109 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl8 : Real.log (46 : ℝ) ≤ (382864139769 / 100000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (46 : ℝ)) (z := (7 / 39 : ℝ)) (U := (382864139769 / 100000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl9 : Real.log (44 : ℝ) ≤ (3784189635119 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (44 : ℝ)) (z := (3 / 19 : ℝ)) (U := (3784189635119 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl10 : Real.log (42 : ℝ) ≤ (934417404871 / 250000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (42 : ℝ)) (z := (5 / 37 : ℝ)) (U := (934417404871 / 250000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl11 : Real.log (40 : ℝ) ≤ (737775891063 / 200000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (40 : ℝ)) (z := (1 / 9 : ℝ)) (U := (737775891063 / 200000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl12 : Real.log (38 : ℝ) ≤ (3637586160927 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (38 : ℝ)) (z := (3 / 35 : ℝ)) (U := (3637586160927 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl13 : Real.log (36 : ℝ) ≤ (3583518939657 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (36 : ℝ)) (z := (1 / 17 : ℝ)) (U := (3583518939657 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl14 : Real.log (34 : ℝ) ≤ (3526360525817 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (34 : ℝ)) (z := (1 / 33 : ℝ)) (U := (3526360525817 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl15 : Real.log (32 : ℝ) ≤ (108304247 / 31250000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (32 : ℝ)) (z := (0 : ℝ)) (U := (108304247 / 31250000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl16 : Real.log (30 : ℝ) ≤ (212574836441 / 62500000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (30 : ℝ)) (z := (7 / 23 : ℝ)) (U := (212574836441 / 62500000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl17 : Real.log (28 : ℝ) ≤ (3332204511217 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (28 : ℝ)) (z := (3 / 11 : ℝ)) (U := (3332204511217 / 1000000000000 : ℝ)) 4 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem cl18 : (481268450043 / 125000000000 : ℝ) ≤ Real.log (47 : ℝ) := by
  have h := (le_log_of_mul_le (q := (47 : ℝ)) (z := (15 / 79 : ℝ)) (L := (481268450043 / 125000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem cl19 : (3871201009477 / 1000000000000 : ℝ) ≤ Real.log (48 : ℝ) := by
  have h := (le_log_of_mul_le (q := (48 : ℝ)) (z := (1 / 5 : ℝ)) (L := (3871201009477 / 1000000000000 : ℝ)) 5 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem cl20 : Real.log (25362 : ℝ) ≤ (5070503636579 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (25362 : ℝ)) (z := (4489 / 20873 : ℝ)) (U := (5070503636579 / 500000000000 : ℝ)) 14 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca1 : Real.arctan (53 / 3 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(3533964809 / 62500000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (53 / 3 : ℝ)) (w := (3 / 53 : ℝ)) (L := (3533964809 / 62500000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg1 : Gf (159 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (129340237456713 / 200000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (159 : ℝ)) (y := (9 : ℝ)) (Q := (25362 : ℝ)) (V := (53 / 3 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl20, ca1]

theorem cl21 : Real.log (82 : ℝ) ≤ (881343849741 / 200000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (82 : ℝ)) (z := (9 / 73 : ℝ)) (U := (881343849741 / 200000000000 : ℝ)) 6 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca2 : Real.arctan (1 / 9 : ℝ) ≤ (0 : ℝ) * π + (55328610587 / 500000000000 : ℝ) := by
  have h := (arctan_le_R1 (u := (1 / 9 : ℝ)) (U := (55328610587 / 500000000000 : ℝ)) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg2 : Gf (1 : ℝ) (9 : ℝ) ≤ (0 : ℝ) * π + (4398549229837 / 2000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (1 : ℝ)) (y := (9 : ℝ)) (Q := (82 : ℝ)) (V := (1 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl21, ca2]

theorem cl22 : (9443434250467 / 1000000000000 : ℝ) ≤ Real.log (12625 : ℝ) := by
  have h := (le_log_of_mul_le (q := (12625 : ℝ)) (z := (4433 / 20817 : ℝ)) (L := (9443434250467 / 1000000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca3 : (1 / 2 : ℝ) * π + (-(40092423651 / 500000000000) : ℝ) ≤ Real.arctan (112 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (112 / 9 : ℝ)) (w := (9 / 112 : ℝ)) (U := (40092423651 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg3 : (9 / 2 : ℝ) * π + (208055327200217 / 500000000000 : ℝ) ≤ Gf (112 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (112 : ℝ)) (y := (9 : ℝ)) (Q := (12625 : ℝ)) (V := (112 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl22, ca3]

theorem cl23 : Real.log (2197 : ℝ) ≤ (3847424037513 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2197 : ℝ)) (z := (149 / 4245 : ℝ)) (U := (3847424037513 / 500000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca4 : Real.arctan (46 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(193211483847 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (46 / 9 : ℝ)) (w := (9 / 46 : ℝ)) (L := (193211483847 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg4 : Gf (46 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (5169704094839 / 40000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (46 : ℝ)) (y := (9 : ℝ)) (Q := (2197 : ℝ)) (V := (46 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl23, ca4]

theorem cl24 : (2356403256339 / 250000000000 : ℝ) ≤ Real.log (12402 : ℝ) := by
  have h := (le_log_of_mul_le (q := (12402 : ℝ)) (z := (2105 / 10297 : ℝ)) (L := (2356403256339 / 250000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca5 : (1 / 2 : ℝ) * π + (-(20226024789 / 250000000000) : ℝ) ≤ Real.arctan (37 / 3 : ℝ) := by
  have h := (arctan_ge_R4 (u := (37 / 3 : ℝ)) (w := (3 / 37 : ℝ)) (U := (20226024789 / 250000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg5 : (9 / 2 : ℝ) * π + (205696693007427 / 500000000000 : ℝ) ≤ Gf (111 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (111 : ℝ)) (y := (9 : ℝ)) (Q := (12402 : ℝ)) (V := (37 / 3 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl24, ca5]

theorem cl25 : Real.log (2290 : ℝ) ≤ (7736307099189 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2290 : ℝ)) (z := (121 / 2169 : ℝ)) (U := (7736307099189 / 1000000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca6 : Real.arctan (47 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(189199022099 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (47 / 9 : ℝ)) (w := (9 / 47 : ℝ)) (L := (189199022099 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg6 : Gf (47 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (266200851264101 / 2000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (47 : ℝ)) (y := (9 : ℝ)) (Q := (2290 : ℝ)) (V := (47 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl25, ca6]

theorem cl26 : (938949023417 / 100000000000 : ℝ) ≤ Real.log (11962 : ℝ) := by
  have h := (le_log_of_mul_le (q := (11962 : ℝ)) (z := (1885 / 10077 : ℝ)) (L := (938949023417 / 100000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca7 : (1 / 2 : ℝ) * π + (-(2574435331 / 31250000000) : ℝ) ≤ Real.arctan (109 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (109 / 9 : ℝ)) (w := (9 / 109 : ℝ)) (U := (2574435331 / 31250000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg7 : (9 / 2 : ℝ) * π + (401985780386937 / 1000000000000 : ℝ) ≤ Gf (109 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (109 : ℝ)) (y := (9 : ℝ)) (Q := (11962 : ℝ)) (V := (109 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl26, ca7]

theorem cl27 : Real.log (2482 : ℝ) ≤ (3908409984203 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2482 : ℝ)) (z := (217 / 2265 : ℝ)) (U := (3908409984203 / 500000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca8 : Real.arctan (49 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(181648829999 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (49 / 9 : ℝ)) (w := (9 / 49 : ℝ)) (L := (181648829999 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg8 : Gf (49 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (35219312438989 / 250000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (49 : ℝ)) (y := (9 : ℝ)) (Q := (2482 : ℝ)) (V := (49 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl27, ca8]

theorem cl28 : (2342795723421 / 250000000000 : ℝ) ≤ Real.log (11745 : ℝ) := by
  have h := (le_log_of_mul_le (q := (11745 : ℝ)) (z := (3553 / 19937 : ℝ)) (L := (2342795723421 / 250000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca9 : (1 / 2 : ℝ) * π + (-(83141231889 / 1000000000000) : ℝ) ≤ Real.arctan (12 : ℝ) := by
  have h := (arctan_ge_R4 (u := (12 : ℝ)) (w := (1 / 12 : ℝ)) (U := (83141231889 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg9 : (9 / 2 : ℝ) * π + (79459121034387 / 200000000000 : ℝ) ≤ Gf (108 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (108 : ℝ)) (y := (9 : ℝ)) (Q := (11745 : ℝ)) (V := (12 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl28, ca9]

theorem cl29 : Real.log (2581 : ℝ) ≤ (196398305059 / 25000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2581 : ℝ)) (z := (533 / 4629 : ℝ)) (U := (196398305059 / 25000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca10 : Real.arctan (50 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(178092938231 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (50 / 9 : ℝ)) (w := (9 / 50 : ℝ)) (L := (178092938231 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg10 : Gf (50 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (144795468614921 / 1000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (50 : ℝ)) (y := (9 : ℝ)) (Q := (2581 : ℝ)) (V := (50 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl29, ca10]

theorem cl30 : (9352707609869 / 1000000000000 : ℝ) ≤ Real.log (11530 : ℝ) := by
  have h := (le_log_of_mul_le (q := (11530 : ℝ)) (z := (1669 / 9861 : ℝ)) (L := (9352707609869 / 1000000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca11 : (1 / 2 : ℝ) * π + (-(4195731347 / 50000000000) : ℝ) ≤ Real.arctan (107 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (107 / 9 : ℝ)) (w := (9 / 107 : ℝ)) (U := (4195731347 / 50000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg11 : (9 / 2 : ℝ) * π + (785229250971063 / 2000000000000 : ℝ) ≤ Gf (107 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (107 : ℝ)) (y := (9 : ℝ)) (Q := (11530 : ℝ)) (V := (107 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl30, ca11]

theorem cl31 : Real.log (2682 : ℝ) ≤ (7894318066483 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2682 : ℝ)) (z := (317 / 2365 : ℝ)) (U := (7894318066483 / 1000000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca12 : Real.arctan (17 / 3 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(5458506219 / 31250000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (17 / 3 : ℝ)) (w := (3 / 17 : ℝ)) (L := (5458506219 / 31250000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg12 : Gf (51 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (297466121808489 / 2000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (51 : ℝ)) (y := (9 : ℝ)) (Q := (2682 : ℝ)) (V := (17 / 3 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl31, ca12]

theorem cl32 : (9334061295579 / 1000000000000 : ℝ) ≤ Real.log (11317 : ℝ) := by
  have h := (le_log_of_mul_le (q := (11317 : ℝ)) (z := (3125 / 19509 : ℝ)) (L := (9334061295579 / 1000000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca13 : (1 / 2 : ℝ) * π + (-(8470251087 / 100000000000) : ℝ) ≤ Real.arctan (106 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (106 / 9 : ℝ)) (w := (9 / 106 : ℝ)) (U := (8470251087 / 100000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg13 : (9 / 2 : ℝ) * π + (387942926067857 / 1000000000000 : ℝ) ≤ Gf (106 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (106 : ℝ)) (y := (9 : ℝ)) (Q := (11317 : ℝ)) (V := (106 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl32, ca13]

theorem cl33 : Real.log (2785 : ℝ) ≤ (3966001577501 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2785 : ℝ)) (z := (737 / 4833 : ℝ)) (U := (3966001577501 / 500000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca14 : Real.arctan (52 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(171379126389 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (52 / 9 : ℝ)) (w := (9 / 52 : ℝ)) (L := (171379126389 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg14 : Gf (52 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (152689669892551 / 1000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (52 : ℝ)) (y := (9 : ℝ)) (Q := (2785 : ℝ)) (V := (52 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl33, ca14]

theorem cl34 : (4657620389209 / 500000000000 : ℝ) ≤ Real.log (11106 : ℝ) := by
  have h := (le_log_of_mul_le (q := (11106 : ℝ)) (z := (1457 / 9649 : ℝ)) (L := (4657620389209 / 500000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca15 : (1 / 2 : ℝ) * π + (-(85505293679 / 1000000000000) : ℝ) ≤ Real.arctan (35 / 3 : ℝ) := by
  have h := (arctan_ge_R4 (u := (35 / 3 : ℝ)) (w := (3 / 35 : ℝ)) (U := (85505293679 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg15 : (9 / 2 : ℝ) * π + (191640296611917 / 500000000000 : ℝ) ≤ Gf (105 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (105 : ℝ)) (y := (9 : ℝ)) (Q := (11106 : ℝ)) (V := (35 / 3 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl34, ca15]

theorem cl35 : Real.log (2890 : ℝ) ≤ (1992252945937 / 250000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2890 : ℝ)) (z := (421 / 2469 : ℝ)) (U := (1992252945937 / 250000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca16 : Real.arctan (53 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(168206771857 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (53 / 9 : ℝ)) (w := (9 / 53 : ℝ)) (L := (168206771857 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg16 : Gf (53 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (156664951322609 / 1000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (53 : ℝ)) (y := (9 : ℝ)) (Q := (2890 : ℝ)) (V := (53 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl35, ca16]

theorem cl36 : (2324060699399 / 250000000000 : ℝ) ≤ Real.log (10897 : ℝ) := by
  have h := (le_log_of_mul_le (q := (10897 : ℝ)) (z := (2705 / 19089 : ℝ)) (L := (2324060699399 / 250000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca17 : (1 / 2 : ℝ) * π + (-(86323400941 / 1000000000000) : ℝ) ≤ Real.arctan (104 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (104 / 9 : ℝ)) (w := (9 / 104 : ℝ)) (U := (86323400941 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg17 : (9 / 2 : ℝ) * π + (378627714866523 / 1000000000000 : ℝ) ≤ Gf (104 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (104 : ℝ)) (y := (9 : ℝ)) (Q := (10897 : ℝ)) (V := (104 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl36, ca17]

theorem cl37 : Real.log (2997 : ℝ) ≤ (4002683534979 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (2997 : ℝ)) (z := (949 / 5045 : ℝ)) (U := (4002683534979 / 500000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca18 : Real.arctan (6 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(82574338707 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (6 : ℝ)) (w := (1 / 6 : ℝ)) (L := (82574338707 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg18 : Gf (54 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (8032928639607 / 50000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (54 : ℝ)) (y := (9 : ℝ)) (Q := (2997 : ℝ)) (V := (6 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl37, ca18]

theorem cl38 : (9277064000639 / 1000000000000 : ℝ) ≤ Real.log (10690 : ℝ) := by
  have h := (le_log_of_mul_le (q := (10690 : ℝ)) (z := (1249 / 9441 : ℝ)) (L := (9277064000639 / 1000000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca19 : (1 / 2 : ℝ) * π + (-(17431454911 / 200000000000) : ℝ) ≤ Real.arctan (103 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (103 / 9 : ℝ)) (w := (9 / 103 : ℝ)) (U := (17431454911 / 200000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg19 : (9 / 2 : ℝ) * π + (747968761123827 / 2000000000000 : ℝ) ≤ Gf (103 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (103 : ℝ)) (y := (9 : ℝ)) (Q := (10690 : ℝ)) (V := (103 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl38, ca19]

theorem cl39 : Real.log (3106 : ℝ) ≤ (8041091006351 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (3106 : ℝ)) (z := (529 / 2577 : ℝ)) (U := (8041091006351 / 1000000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca20 : Real.arctan (55 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(162198833463 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (55 / 9 : ℝ)) (w := (9 / 55 : ℝ)) (L := (162198833463 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg20 : Gf (55 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (329340426346971 / 2000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (55 : ℝ)) (y := (9 : ℝ)) (Q := (3106 : ℝ)) (V := (55 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl39, ca20]

theorem cl40 : (2314425234989 / 250000000000 : ℝ) ≤ Real.log (10485 : ℝ) := by
  have h := (le_log_of_mul_le (q := (10485 : ℝ)) (z := (2293 / 18677 : ℝ)) (L := (2314425234989 / 250000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca21 : (1 / 2 : ℝ) * π + (-(11000921691 / 125000000000) : ℝ) ≤ Real.arctan (34 / 3 : ℝ) := by
  have h := (arctan_ge_R4 (u := (34 / 3 : ℝ)) (w := (3 / 34 : ℝ)) (U := (11000921691 / 125000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg21 : (9 / 2 : ℝ) * π + (92337670394001 / 250000000000 : ℝ) ≤ Gf (102 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (102 : ℝ)) (y := (9 : ℝ)) (Q := (10485 : ℝ)) (V := (34 / 3 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl40, ca21]

theorem cl41 : Real.log (3217 : ℝ) ≤ (2019051132471 / 250000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (3217 : ℝ)) (z := (1169 / 5265 : ℝ)) (U := (2019051132471 / 250000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca22 : Real.arctan (56 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(159351640903 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (56 / 9 : ℝ)) (w := (9 / 56 : ℝ)) (L := (159351640903 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg22 : Gf (56 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (1349596496549 / 8000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (56 : ℝ)) (y := (9 : ℝ)) (Q := (3217 : ℝ)) (V := (56 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl41, ca22]

theorem cl42 : (2309537517309 / 250000000000 : ℝ) ≤ Real.log (10282 : ℝ) := by
  have h := (le_log_of_mul_le (q := (10282 : ℝ)) (z := (1045 / 9237 : ℝ)) (L := (2309537517309 / 250000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca23 : (1 / 2 : ℝ) * π + (-(44437087407 / 500000000000) : ℝ) ≤ Real.arctan (101 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (101 / 9 : ℝ)) (w := (9 / 101 : ℝ)) (U := (44437087407 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg23 : (9 / 2 : ℝ) * π + (91181677730773 / 250000000000 : ℝ) ≤ Gf (101 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (101 : ℝ)) (y := (9 : ℝ)) (Q := (10282 : ℝ)) (V := (101 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl42, ca23]

theorem cl43 : Real.log (3330 : ℝ) ≤ (4055363792813 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (3330 : ℝ)) (z := (641 / 2689 : ℝ)) (U := (4055363792813 / 500000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca24 : Real.arctan (19 / 3 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(78300938491 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (19 / 3 : ℝ)) (w := (3 / 19 : ℝ)) (L := (78300938491 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg24 : Gf (57 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (172746319297503 / 1000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (57 : ℝ)) (y := (9 : ℝ)) (Q := (3330 : ℝ)) (V := (19 / 3 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl43, ca24]

theorem cl44 : (4609203869837 / 500000000000 : ℝ) ≤ Real.log (10081 : ℝ) := by
  have h := (le_log_of_mul_le (q := (10081 : ℝ)) (z := (1889 / 18273 : ℝ)) (L := (4609203869837 / 500000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca25 : (1 / 2 : ℝ) * π + (-(8975817419 / 100000000000) : ℝ) ≤ Real.arctan (100 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (100 / 9 : ℝ)) (w := (9 / 100 : ℝ)) (U := (8975817419 / 100000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg25 : (9 / 2 : ℝ) * π + (36011256341599 / 100000000000 : ℝ) ≤ Gf (100 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (100 : ℝ)) (y := (9 : ℝ)) (Q := (10081 : ℝ)) (V := (100 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl44, ca25]

theorem cl45 : Real.log (3445 : ℝ) ≤ (8144679186117 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (3445 : ℝ)) (z := (1397 / 5493 : ℝ)) (U := (8144679186117 / 1000000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca26 : Real.arctan (58 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(76972332229 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (58 / 9 : ℝ)) (w := (9 / 58 : ℝ)) (L := (76972332229 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg26 : Gf (58 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (176810194417271 / 1000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (58 : ℝ)) (y := (9 : ℝ)) (Q := (3445 : ℝ)) (V := (58 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl45, ca26]

theorem cl46 : (4599235098013 / 500000000000 : ℝ) ≤ Real.log (9882 : ℝ) := by
  have h := (le_log_of_mul_le (q := (9882 : ℝ)) (z := (845 / 9037 : ℝ)) (L := (4599235098013 / 500000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca27 : (1 / 2 : ℝ) * π + (-(90659887201 / 1000000000000) : ℝ) ≤ Real.arctan (11 : ℝ) := by
  have h := (arctan_ge_R4 (u := (11 : ℝ)) (w := (1 / 11 : ℝ)) (U := (90659887201 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg27 : (9 / 2 : ℝ) * π + (177754167859239 / 500000000000 : ℝ) ≤ Gf (99 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (99 : ℝ)) (y := (9 : ℝ)) (Q := (9882 : ℝ)) (V := (11 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl46, ca27]

theorem cl47 : Real.log (3562 : ℝ) ≤ (8178077466559 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (3562 : ℝ)) (z := (757 / 2805 : ℝ)) (U := (8178077466559 / 1000000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca28 : Real.arctan (59 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(75687721867 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (59 / 9 : ℝ)) (w := (9 / 59 : ℝ)) (L := (75687721867 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg28 : Gf (59 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (361781812539769 / 2000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (59 : ℝ)) (y := (9 : ℝ)) (Q := (3562 : ℝ)) (V := (59 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl47, ca28]

theorem cl48 : (9178333572461 / 1000000000000 : ℝ) ≤ Real.log (9685 : ℝ) := by
  have h := (le_log_of_mul_le (q := (9685 : ℝ)) (z := (1493 / 17877 : ℝ)) (L := (9178333572461 / 1000000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca29 : (1 / 2 : ℝ) * π + (-(91579850143 / 1000000000000) : ℝ) ≤ Real.arctan (98 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (98 / 9 : ℝ)) (w := (9 / 98 : ℝ)) (U := (91579850143 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg29 : (9 / 2 : ℝ) * π + (175457063199651 / 500000000000 : ℝ) ≤ Gf (98 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (98 : ℝ)) (y := (9 : ℝ)) (Q := (9685 : ℝ)) (V := (98 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl48, ca29]

theorem cl49 : Real.log (3681 : ℝ) ≤ (8210939736179 / 1000000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (3681 : ℝ)) (z := (1633 / 5729 : ℝ)) (U := (8210939736179 / 1000000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca30 : Real.arctan (20 / 3 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(148889947609 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (20 / 3 : ℝ)) (w := (3 / 20 : ℝ)) (L := (148889947609 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg30 : Gf (60 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (184988182556889 / 1000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (60 : ℝ)) (y := (9 : ℝ)) (Q := (3681 : ℝ)) (V := (20 / 3 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl49, ca30]

theorem cl50 : (286187309007 / 31250000000 : ℝ) ≤ Real.log (9490 : ℝ) := by
  have h := (le_log_of_mul_le (q := (9490 : ℝ)) (z := (649 / 8841 : ℝ)) (L := (286187309007 / 31250000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca31 : (1 / 2 : ℝ) * π + (-(289120691 / 3125000000) : ℝ) ≤ Real.arctan (97 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (97 / 9 : ℝ)) (w := (9 / 97 : ℝ)) (U := (289120691 / 3125000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg31 : (9 / 2 : ℝ) * π + (21645627249299 / 62500000000 : ℝ) ≤ Gf (97 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (97 : ℝ)) (y := (9 : ℝ)) (Q := (9490 : ℝ)) (V := (97 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl50, ca31]

theorem cl51 : Real.log (3802 : ℝ) ≤ (4121641263017 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (3802 : ℝ)) (z := (877 / 2925 : ℝ)) (U := (4121641263017 / 500000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca32 : Real.arctan (61 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(146484178393 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (61 / 9 : ℝ)) (w := (9 / 61 : ℝ)) (L := (146484178393 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg32 : Gf (61 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (378203518877 / 2000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (61 : ℝ)) (y := (9 : ℝ)) (Q := (3802 : ℝ)) (V := (61 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl51, ca32]

theorem cl52 : (2284361760769 / 250000000000 : ℝ) ≤ Real.log (9297 : ℝ) := by
  have h := (le_log_of_mul_le (q := (9297 : ℝ)) (z := (1105 / 17489 : ℝ)) (L := (2284361760769 / 250000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca33 : (1 / 2 : ℝ) * π + (-(93476781159 / 1000000000000) : ℝ) ≤ Real.arctan (32 / 3 : ℝ) := by
  have h := (arctan_ge_R4 (u := (32 / 3 : ℝ)) (w := (3 / 32 : ℝ)) (U := (93476781159 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg33 : (9 / 2 : ℝ) * π + (341756167037217 / 1000000000000 : ℝ) ≤ Gf (96 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (96 : ℝ)) (y := (9 : ℝ)) (Q := (9297 : ℝ)) (V := (32 / 3 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl52, ca33]

theorem cl53 : Real.log (3925 : ℝ) ≤ (4137560816783 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (3925 : ℝ)) (z := (1877 / 5973 : ℝ)) (U := (4137560816783 / 500000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca34 : Real.arctan (62 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(144154387113 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (62 / 9 : ℝ)) (w := (9 / 62 : ℝ)) (L := (144154387113 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg34 : Gf (62 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (193231381156529 / 1000000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (62 : ℝ)) (y := (9 : ℝ)) (Q := (3925 : ℝ)) (V := (62 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl53, ca34]

theorem cl54 : (1823337762503 / 200000000000 : ℝ) ≤ Real.log (9106 : ℝ) := by
  have h := (le_log_of_mul_le (q := (9106 : ℝ)) (z := (457 / 8649 : ℝ)) (L := (1823337762503 / 200000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca35 : (1 / 2 : ℝ) * π + (-(23613733849 / 250000000000) : ℝ) ≤ Real.arctan (95 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (95 / 9 : ℝ)) (w := (9 / 95 : ℝ)) (U := (23613733849 / 250000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg35 : (9 / 2 : ℝ) * π + (674385248351797 / 2000000000000 : ℝ) ≤ Gf (95 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (95 : ℝ)) (y := (9 : ℝ)) (Q := (9106 : ℝ)) (V := (95 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl54, ca35]

theorem cl55 : Real.log (4050 : ℝ) ≤ (2076618041033 / 250000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (4050 : ℝ)) (z := (1001 / 3049 : ℝ)) (U := (2076618041033 / 250000000000 : ℝ)) 11 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca36 : Real.arctan (7 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(35474263651 / 250000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (7 : ℝ)) (w := (1 / 7 : ℝ)) (L := (35474263651 / 250000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg36 : Gf (63 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (98688399839361 / 500000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (63 : ℝ)) (y := (9 : ℝ)) (Q := (4050 : ℝ)) (V := (7 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl55, ca36]

theorem cl56 : (1819142968551 / 200000000000 : ℝ) ≤ Real.log (8917 : ℝ) := by
  have h := (le_log_of_mul_le (q := (8917 : ℝ)) (z := (725 / 17109 : ℝ)) (L := (1819142968551 / 200000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca37 : (1 / 2 : ℝ) * π + (-(95453714333 / 1000000000000) : ℝ) ≤ Real.arctan (94 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (94 / 9 : ℝ)) (w := (9 / 94 : ℝ)) (U := (95453714333 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg37 : (9 / 2 : ℝ) * π + (41579939272561 / 125000000000 : ℝ) ≤ Gf (94 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (94 : ℝ)) (y := (9 : ℝ)) (Q := (8917 : ℝ)) (V := (94 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl56, ca37]

theorem cl57 : Real.log (4177 : ℝ) ≤ (4168674283689 / 500000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (4177 : ℝ)) (z := (81 / 8273 : ℝ)) (U := (4168674283689 / 500000000000 : ℝ)) 12 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca38 : Real.arctan (64 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(139708874289 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (64 / 9 : ℝ)) (w := (9 / 64 : ℝ)) (L := (139708874289 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg38 : Gf (64 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (40307554857499 / 200000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (64 : ℝ)) (y := (9 : ℝ)) (Q := (4177 : ℝ)) (V := (64 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl57, ca38]

theorem cl58 : (4537260322727 / 500000000000 : ℝ) ≤ Real.log (8730 : ℝ) := by
  have h := (le_log_of_mul_le (q := (8730 : ℝ)) (z := (269 / 8461 : ℝ)) (L := (4537260322727 / 500000000000 : ℝ)) 13 (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog]))
  linarith

theorem ca39 : (1 / 2 : ℝ) * π + (-(96473775183 / 1000000000000) : ℝ) ≤ Real.arctan (31 / 3 : ℝ) := by
  have h := (arctan_ge_R4 (u := (31 / 3 : ℝ)) (w := (3 / 31 : ℝ)) (U := (96473775183 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem cg39 : (9 / 2 : ℝ) * π + (82024236509241 / 250000000000 : ℝ) ≤ Gf (93 : ℝ) (9 : ℝ) := by
  rw [Gf_eq_pos (a := (93 : ℝ)) (y := (9 : ℝ)) (Q := (8730 : ℝ)) (V := (31 / 3 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl58, ca39]

theorem cl59 : Real.log (4306 : ℝ) ≤ (1673552936161 / 200000000000 : ℝ) := by
  have h := (log_le_of_le_mul (q := (4306 : ℝ)) (z := (105 / 4201 : ℝ)) (U := (1673552936161 / 200000000000 : ℝ)) 12 (by norm_num) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Slog, Rlog]))
  linarith

theorem ca40 : Real.arctan (65 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(13758673647 / 100000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (65 / 9 : ℝ)) (w := (9 / 65 : ℝ)) (L := (13758673647 / 100000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem cg40 : Gf (65 : ℝ) (9 : ℝ) ≤ (9 / 2 : ℝ) * π + (82285628599173 / 400000000000 : ℝ) := by
  rw [Gf_eq_pos (a := (65 : ℝ)) (y := (9 : ℝ)) (Q := (4306 : ℝ)) (V := (65 / 9 : ℝ)) (by norm_num) (by norm_num)]
  linarith [cl59, ca40]

theorem ca41 : (1 / 2 : ℝ) * π + (-(11308687389 / 200000000000) : ℝ) ≤ Real.arctan (53 / 3 : ℝ) := by
  have h := (arctan_ge_R4 (u := (53 / 3 : ℝ)) (w := (3 / 53 : ℝ)) (U := (11308687389 / 200000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca42 : (0 : ℝ) * π + (110657221173 / 1000000000000 : ℝ) ≤ Real.arctan (1 / 9 : ℝ) := by
  have h := (arctan_ge_R1 (u := (1 / 9 : ℝ)) (L := (110657221173 / 1000000000000 : ℝ)) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca43 : Real.arctan (112 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(80184847301 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (112 / 9 : ℝ)) (w := (9 / 112 : ℝ)) (L := (80184847301 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca44 : (1 / 2 : ℝ) * π + (-(24151435481 / 125000000000) : ℝ) ≤ Real.arctan (46 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (46 / 9 : ℝ)) (w := (9 / 46 : ℝ)) (U := (24151435481 / 125000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca45 : Real.arctan (37 / 3 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(16180819831 / 200000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (37 / 3 : ℝ)) (w := (3 / 37 : ℝ)) (L := (16180819831 / 200000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca46 : (1 / 2 : ℝ) * π + (-(1891990221 / 10000000000) : ℝ) ≤ Real.arctan (47 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (47 / 9 : ℝ)) (w := (9 / 47 : ℝ)) (U := (1891990221 / 10000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca47 : Real.arctan (109 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(82381930591 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (109 / 9 : ℝ)) (w := (9 / 109 : ℝ)) (L := (82381930591 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca48 : (1 / 2 : ℝ) * π + (-(181648830001 / 1000000000000) : ℝ) ≤ Real.arctan (49 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (49 / 9 : ℝ)) (w := (9 / 49 : ℝ)) (U := (181648830001 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca49 : Real.arctan (12 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(5196326993 / 62500000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (12 : ℝ)) (w := (1 / 12 : ℝ)) (L := (5196326993 / 62500000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca50 : (1 / 2 : ℝ) * π + (-(22261617279 / 125000000000) : ℝ) ≤ Real.arctan (50 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (50 / 9 : ℝ)) (w := (9 / 50 : ℝ)) (U := (22261617279 / 125000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca51 : Real.arctan (107 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(83914626939 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (107 / 9 : ℝ)) (w := (9 / 107 : ℝ)) (L := (83914626939 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca52 : (1 / 2 : ℝ) * π + (-(174672199009 / 1000000000000) : ℝ) ≤ Real.arctan (17 / 3 : ℝ) := by
  have h := (arctan_ge_R4 (u := (17 / 3 : ℝ)) (w := (3 / 17 : ℝ)) (U := (174672199009 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca53 : Real.arctan (106 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(84702510869 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (106 / 9 : ℝ)) (w := (9 / 106 : ℝ)) (L := (84702510869 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca54 : (1 / 2 : ℝ) * π + (-(17137912639 / 100000000000) : ℝ) ≤ Real.arctan (52 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (52 / 9 : ℝ)) (w := (9 / 52 : ℝ)) (U := (17137912639 / 100000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca55 : Real.arctan (35 / 3 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(42752646839 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (35 / 3 : ℝ)) (w := (3 / 35 : ℝ)) (L := (42752646839 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca56 : (1 / 2 : ℝ) * π + (-(84103385929 / 500000000000) : ℝ) ≤ Real.arctan (53 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (53 / 9 : ℝ)) (w := (9 / 53 : ℝ)) (U := (84103385929 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca57 : Real.arctan (104 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(4316170047 / 50000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (104 / 9 : ℝ)) (w := (9 / 104 : ℝ)) (L := (4316170047 / 50000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca58 : (1 / 2 : ℝ) * π + (-(33029735483 / 200000000000) : ℝ) ≤ Real.arctan (6 : ℝ) := by
  have h := (arctan_ge_R4 (u := (6 : ℝ)) (w := (1 / 6 : ℝ)) (U := (33029735483 / 200000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca59 : Real.arctan (103 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(43578637277 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (103 / 9 : ℝ)) (w := (9 / 103 : ℝ)) (L := (43578637277 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca60 : (1 / 2 : ℝ) * π + (-(20274854183 / 125000000000) : ℝ) ≤ Real.arctan (55 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (55 / 9 : ℝ)) (w := (9 / 55 : ℝ)) (U := (20274854183 / 125000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca61 : Real.arctan (34 / 3 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(88007373527 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (34 / 3 : ℝ)) (w := (3 / 34 : ℝ)) (L := (88007373527 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca62 : (1 / 2 : ℝ) * π + (-(19918955113 / 125000000000) : ℝ) ≤ Real.arctan (56 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (56 / 9 : ℝ)) (w := (9 / 56 : ℝ)) (U := (19918955113 / 125000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca63 : Real.arctan (101 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(88874174813 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (101 / 9 : ℝ)) (w := (9 / 101 : ℝ)) (L := (88874174813 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca64 : (1 / 2 : ℝ) * π + (-(156601876983 / 1000000000000) : ℝ) ≤ Real.arctan (19 / 3 : ℝ) := by
  have h := (arctan_ge_R4 (u := (19 / 3 : ℝ)) (w := (3 / 19 : ℝ)) (U := (156601876983 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca65 : Real.arctan (100 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(89758174189 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (100 / 9 : ℝ)) (w := (9 / 100 : ℝ)) (L := (89758174189 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca66 : (1 / 2 : ℝ) * π + (-(153944664459 / 1000000000000) : ℝ) ≤ Real.arctan (58 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (58 / 9 : ℝ)) (w := (9 / 58 : ℝ)) (U := (153944664459 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca67 : Real.arctan (11 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(113324859 / 1250000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (11 : ℝ)) (w := (1 / 11 : ℝ)) (L := (113324859 / 1250000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca68 : (1 / 2 : ℝ) * π + (-(30275088747 / 200000000000) : ℝ) ≤ Real.arctan (59 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (59 / 9 : ℝ)) (w := (9 / 59 : ℝ)) (U := (30275088747 / 200000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca69 : Real.arctan (98 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(45789925071 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (98 / 9 : ℝ)) (w := (9 / 98 : ℝ)) (L := (45789925071 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca70 : (1 / 2 : ℝ) * π + (-(14888994761 / 100000000000) : ℝ) ≤ Real.arctan (20 / 3 : ℝ) := by
  have h := (arctan_ge_R4 (u := (20 / 3 : ℝ)) (w := (3 / 20 : ℝ)) (U := (14888994761 / 100000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca71 : Real.arctan (97 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(92518621119 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (97 / 9 : ℝ)) (w := (9 / 97 : ℝ)) (L := (92518621119 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca72 : (1 / 2 : ℝ) * π + (-(73242089197 / 500000000000) : ℝ) ≤ Real.arctan (61 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (61 / 9 : ℝ)) (w := (9 / 61 : ℝ)) (U := (73242089197 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca73 : Real.arctan (32 / 3 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(46738390579 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (32 / 3 : ℝ)) (w := (3 / 32 : ℝ)) (L := (46738390579 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca74 : (1 / 2 : ℝ) * π + (-(72077193557 / 500000000000) : ℝ) ≤ Real.arctan (62 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (62 / 9 : ℝ)) (w := (9 / 62 : ℝ)) (U := (72077193557 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca75 : Real.arctan (95 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(18890987079 / 200000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (95 / 9 : ℝ)) (w := (9 / 95 : ℝ)) (L := (18890987079 / 200000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca76 : (1 / 2 : ℝ) * π + (-(28379410921 / 200000000000) : ℝ) ≤ Real.arctan (7 : ℝ) := by
  have h := (arctan_ge_R4 (u := (7 : ℝ)) (w := (1 / 7 : ℝ)) (U := (28379410921 / 200000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca77 : Real.arctan (94 / 9 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(23863428583 / 250000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (94 / 9 : ℝ)) (w := (9 / 94 : ℝ)) (L := (23863428583 / 250000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca78 : (1 / 2 : ℝ) * π + (-(13970887429 / 100000000000) : ℝ) ≤ Real.arctan (64 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (64 / 9 : ℝ)) (w := (9 / 64 : ℝ)) (U := (13970887429 / 100000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca79 : Real.arctan (31 / 3 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(48236887591 / 500000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (31 / 3 : ℝ)) (w := (3 / 31 : ℝ)) (L := (48236887591 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca80 : (1 / 2 : ℝ) * π + (-(137586736471 / 1000000000000) : ℝ) ≤ Real.arctan (65 / 9 : ℝ) := by
  have h := (arctan_ge_R4 (u := (65 / 9 : ℝ)) (w := (9 / 65 : ℝ)) (U := (137586736471 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca81 : Real.arctan (159 / 46 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(281619148849 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (159 / 46 : ℝ)) (w := (46 / 159 : ℝ)) (L := (281619148849 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca82 : Real.arctan (1 / 46 : ℝ) ≤ (0 : ℝ) * π + (10867853421 / 500000000000 : ℝ) := by
  have h := (arctan_le_R1 (u := (1 / 46 : ℝ)) (U := (10867853421 / 500000000000 : ℝ)) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca83 : (1 / 4 : ℝ) * π + (53108005127 / 250000000000 : ℝ) ≤ Real.arctan (31 / 20 : ℝ) := by
  have h := (arctan_ge_R3 (u := (31 / 20 : ℝ)) (w := (11 / 51 : ℝ)) (L := (53108005127 / 250000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca84 : Real.arctan (65 / 46 : ℝ) ≤ (1 / 4 : ℝ) * π + (84764105729 / 500000000000 : ℝ) := by
  have h := (arctan_le_R3 (u := (65 / 46 : ℝ)) (w := (19 / 111 : ℝ)) (U := (84764105729 / 500000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

theorem ca85 : Real.arctan (53 / 20 : ℝ) ≤ (1 / 2 : ℝ) * π + (-(360836779703 / 1000000000000) : ℝ) := by
  have h := (arctan_le_R4 (u := (53 / 20 : ℝ)) (w := (20 / 53 : ℝ)) (L := (360836779703 / 1000000000000 : ℝ)) (by norm_num) (by norm_num) (by norm_num [Pat8]))
  linarith

theorem ca86 : Real.arctan (1 / 60 : ℝ) ≤ (0 : ℝ) * π + (8332561857 / 500000000000 : ℝ) := by
  have h := (arctan_le_R1 (u := (1 / 60 : ℝ)) (U := (8332561857 / 500000000000 : ℝ)) (by norm_num) (by norm_num [Pat9, Pat8]))
  linarith

/-! ## `C_η`, `U(9)`, `U'(9)` -/

theorem Ceta_eq : Ceta = 120 * Real.log 60 + 58 * Real.log 58 + 56 * Real.log 56 + 54 * Real.log 54 + 52 * Real.log 52 + 50 * Real.log 50 + 48 * Real.log 48 + 46 * Real.log 46 + 44 * Real.log 44 + 42 * Real.log 42 + 40 * Real.log 40 + 38 * Real.log 38 + 36 * Real.log 36 + 34 * Real.log 34 + 32 * Real.log 32 + 30 * Real.log 30 + 28 * Real.log 28 - 2 * (188 * Real.log 47 + 48 * Real.log 48) := by
  unfold Ceta
  rw [show Finset.Icc 6 23 = Finset.Ico 6 24 by decide, show Finset.Icc 1 5 = Finset.Ico 1 6 by decide,
    Finset.sum_Ico_eq_sum_range, Finset.sum_Ico_eq_sum_range]
  norm_num [Finset.sum_range_succ, etaW]
  ring

theorem Ceta_le : Ceta ≤ 255155223 / 200000 := by
  rw [Ceta_eq]
  linarith [cl1, cl2, cl3, cl4, cl5, cl6, cl7, cl8, cl9, cl10, cl11, cl12, cl13, cl14, cl15, cl16, cl17, cl18, cl19]

theorem Uw9_eq : Uw 9 = Ceta - 336 + 5 * (Gf 159 9 + Gf 1 9) - (4 * (Gf 112 9 - Gf 46 9) + (Gf 111 9 - Gf 47 9) + 2 * (Gf 109 9 - Gf 49 9) + (Gf 108 9 - Gf 50 9) + (Gf 107 9 - Gf 51 9) + (Gf 106 9 - Gf 52 9) + (Gf 105 9 - Gf 53 9) + (Gf 104 9 - Gf 54 9) + (Gf 103 9 - Gf 55 9) + (Gf 102 9 - Gf 56 9) + (Gf 101 9 - Gf 57 9) + (Gf 100 9 - Gf 58 9) + (Gf 99 9 - Gf 59 9) + (Gf 98 9 - Gf 60 9) + (Gf 97 9 - Gf 61 9) + (Gf 96 9 - Gf 62 9) + (Gf 95 9 - Gf 63 9) + (Gf 94 9 - Gf 64 9) + (Gf 93 9 - Gf 65 9)) - 2 * π * 9 := by
  unfold Uw
  rw [show Gf (-1) 9 = -Gf 1 9 from Gf_neg 1 9]
  rw [show Finset.Icc 1 23 = Finset.Ico 1 24 by decide, Finset.sum_Ico_eq_sum_range]
  norm_num [Finset.sum_range_succ, etaW]
  ring

theorem Uw9_le : Uw 9 ≤ -(750631301 / 1000000) := by
  rw [Uw9_eq]
  linarith [Ceta_le, cg1, cg2, cg3, cg4, cg5, cg6, cg7, cg8, cg9, cg10, cg11, cg12, cg13, cg14, cg15, cg16, cg17, cg18, cg19, cg20, cg21, cg22, cg23, cg24, cg25, cg26, cg27, cg28, cg29, cg30, cg31, cg32, cg33, cg34, cg35, cg36, cg37, cg38, cg39, cg40, Real.pi_gt_d20, Real.pi_lt_d20]

theorem dUw9_eq : dUw 9 = 5 * (Real.arctan (53 / 3 : ℝ) + Real.arctan (1 / 9 : ℝ)) - (4 * (Real.arctan (112 / 9 : ℝ) - Real.arctan (46 / 9 : ℝ)) + (Real.arctan (37 / 3 : ℝ) - Real.arctan (47 / 9 : ℝ)) + 2 * (Real.arctan (109 / 9 : ℝ) - Real.arctan (49 / 9 : ℝ)) + (Real.arctan (12 : ℝ) - Real.arctan (50 / 9 : ℝ)) + (Real.arctan (107 / 9 : ℝ) - Real.arctan (17 / 3 : ℝ)) + (Real.arctan (106 / 9 : ℝ) - Real.arctan (52 / 9 : ℝ)) + (Real.arctan (35 / 3 : ℝ) - Real.arctan (53 / 9 : ℝ)) + (Real.arctan (104 / 9 : ℝ) - Real.arctan (6 : ℝ)) + (Real.arctan (103 / 9 : ℝ) - Real.arctan (55 / 9 : ℝ)) + (Real.arctan (34 / 3 : ℝ) - Real.arctan (56 / 9 : ℝ)) + (Real.arctan (101 / 9 : ℝ) - Real.arctan (19 / 3 : ℝ)) + (Real.arctan (100 / 9 : ℝ) - Real.arctan (58 / 9 : ℝ)) + (Real.arctan (11 : ℝ) - Real.arctan (59 / 9 : ℝ)) + (Real.arctan (98 / 9 : ℝ) - Real.arctan (20 / 3 : ℝ)) + (Real.arctan (97 / 9 : ℝ) - Real.arctan (61 / 9 : ℝ)) + (Real.arctan (32 / 3 : ℝ) - Real.arctan (62 / 9 : ℝ)) + (Real.arctan (95 / 9 : ℝ) - Real.arctan (7 : ℝ)) + (Real.arctan (94 / 9 : ℝ) - Real.arctan (64 / 9 : ℝ)) + (Real.arctan (31 / 3 : ℝ) - Real.arctan (65 / 9 : ℝ))) - 2 * π := by
  unfold dUw
  rw [show Finset.Icc 1 23 = Finset.Ico 1 24 by decide, Finset.sum_Ico_eq_sum_range]
  norm_num [Finset.sum_range_succ, etaW]
  ring

theorem dUw9_le : dUw 9 ≤ 14739 / 1000000 := by
  rw [dUw9_eq]
  linarith [ca1, ca2, ca3, ca4, ca5, ca6, ca7, ca8, ca9, ca10, ca11, ca12, ca13, ca14, ca15, ca16, ca17, ca18, ca19, ca20, ca21, ca22, ca23, ca24, ca25, ca26, ca27, ca28, ca29, ca30, ca31, ca32, ca33, ca34, ca35, ca36, ca37, ca38, ca39, ca40, Real.pi_gt_d20, Real.pi_lt_d20]

theorem dUw9_ge : 7369 / 500000 ≤ dUw 9 := by
  rw [dUw9_eq]
  linarith [ca41, ca42, ca43, ca44, ca45, ca46, ca47, ca48, ca49, ca50, ca51, ca52, ca53, ca54, ca55, ca56, ca57, ca58, ca59, ca60, ca61, ca62, ca63, ca64, ca65, ca66, ca67, ca68, ca69, ca70, ca71, ca72, ca73, ca74, ca75, ca76, ca77, ca78, ca79, ca80, Real.pi_gt_d20, Real.pi_lt_d20]

theorem cell_le :
    5 * (Real.arctan (159 / 46) + Real.arctan (1 / 46)) -
      23 * (Real.arctan (31 / 20) - Real.arctan (65 / 46)) - 2 * π ≤ -(44713 / 62500) := by
  linarith [ca81, ca82, ca83, ca84, Real.pi_gt_d20, Real.pi_lt_d20]

theorem tail_le : 5 * (Real.arctan (53 / 20) + Real.arctan (1 / 60)) - 2 * π ≤ -(150061 / 1000000) := by
  linarith [ca85, ca86, Real.pi_gt_d20, Real.pi_lt_d20]

end L20U

end ZetaWindow

end
