"""Generate Zeta2Lean/Window/PhiTable.lean: the table of Zudilin's phi(x) = min_y phi0(x, y) on (0, 1)
for the window configuration cfgW (r = 5, q = 23, eta0 = 160, eta = (47,47,47,47,48,50,50,51,...,66)).

Independent of the research engine docs/window/vz.py (which it reproduces; see --crosscheck).  Everything is exact
(fractions.Fraction).  phi0 is transcribed literally from the Lean definition `ZetaWindow.phi0`
(Zeta2Lean/Window/Defs.lean):

  phi0(x, y) = sum_{j<=r} ( [y] + [eta0 x - y] - [y - eta_j x] - [(eta0 - eta_j) x - y] - 2 [eta_j x] )
             + sum_{j>r}  ( [(eta0 - 2 eta_j) x] - [y - eta_j x] - [(eta0 - eta_j) x - y] ),   [.] = floor.

phi0 is 1-periodic in x and y.  For y in [0, 1) every term [a x + b y] (b = +-1) jumps only at
y = frac(-b a x); two such thresholds collide, or a threshold hits 0, or an x-only term [a x] jumps,
only at x in (1/d) Z for d in D = {|a|} u {|b1 a1 - b2 a2|}.  Between consecutive such breakpoints the
combinatorial type is constant, so phi(x) = min over the finitely many y-positions (the thresholds
and the midpoints between consecutive thresholds) evaluated at the midpoint of the piece.

Output: the list of open pieces (a, b) of (0, 1) with value v = phi > 0 (pieces with phi = 0 are
omitted: they contribute nothing), sorted, as `Piece` literals ⟨an, ad, bn, bd, v⟩ (a = an/ad, b = bn/bd).

usage: python3 python/window_phitable.py [--write] [--K 20] [--crosscheck path/to/vz.py]
"""
import sys, math, argparse
from fractions import Fraction as Fr

R = 5
ETA0 = 160
ETA = [47, 47, 47, 47, 48, 50, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66]


def terms(eta0=ETA0, eta=ETA, r=R):
    """(a, b, c): c * floor(a x + b y), literally the Lean phi0 (uncompressed)."""
    T = []
    for j, ej in enumerate(eta, start=1):
        if j <= r:
            T += [(0, 1, 1), (eta0, -1, 1), (-ej, 1, -1), (eta0 - ej, -1, -1), (ej, 0, -2)]
        else:
            T += [(eta0 - 2 * ej, 0, 1), (-ej, 1, -1), (eta0 - ej, -1, -1)]
    return T


def floor(x):
    return x.numerator // x.denominator


def phi0(T, x, y):
    return sum(c * floor(a * x + b * y) for a, b, c in T)


def breakpoints(T):
    D = set(abs(a) for a, b, c in T)
    Y = [(a, b) for a, b, c in T if b != 0]
    for a1, b1 in Y:
        for a2, b2 in Y:
            D.add(abs(b1 * a1 - b2 * a2))
    D.discard(0)
    pts = {Fr(0), Fr(1)}
    for d in D:
        for u in range(1, d):
            pts.add(Fr(u, d))
    return sorted(pts)


def phi_at(T, x):
    """min over y in [0,1) of phi0(x, y) (exact): thresholds and midpoints between them."""
    th = sorted({(-b * a * x) - floor(-b * a * x) for a, b, c in T if b != 0} | {Fr(0)})
    cand = list(th)
    for i in range(len(th)):
        lo = th[i]
        hi = th[i + 1] if i + 1 < len(th) else Fr(1)
        cand.append((lo + hi) / 2)
    return min(phi0(T, x, y) for y in cand)


def pieces(T):
    bp = breakpoints(T)
    out = []
    for i in range(len(bp) - 1):
        a, b = bp[i], bp[i + 1]
        out.append((a, b, phi_at(T, (a + b) / 2)))
    return out


def weight(a, b, v, M, K):
    """phiWeight of the Lean file: v * ((1/a - 1/b if 1/M <= a else 0) + sum_{m=1}^K (1/(a+m) - 1/(b+m)))."""
    s = Fr(0)
    if Fr(1, M) <= a:
        s += 1 / a - 1 / b
    for m in range(1, K + 1):
        s += 1 / (a + m) - 1 / (b + m)
    return v * s


def lean_file(P, K, total):
    lines = []
    lines.append("import Zeta2Lean.Window.Defs")
    lines.append("")
    lines.append("/-!")
    lines.append("# Zeta2Lean.Window.PhiTable — the table of Zudilin's `φ(x) = min_y φ₀(x, y)` on `(0, 1)` for `cfgW`")
    lines.append("")
    lines.append("GENERATED by `python/window_phitable.py --write` (do not edit by hand).  Each entry")
    lines.append("`⟨an, ad, bn, bd, v⟩` is an open interval `(an/ad, bn/bd)` between consecutive breakpoints of `φ`")
    lines.append("on which `φ ≡ v` (the combinatorial type of `φ₀(x, ·)` is constant there).  Pieces with `φ = 0`")
    lines.append(f"are omitted.  {len(P)} pieces; certified sum (`phiSumQ phiTable 60 {K}`) = {float(total):.10f}")
    lines.append(f"(exact value {total.numerator.bit_length()}-bit numerator), so `muSum cfgW - phiSumQ … = 1341 - {float(total):.6f}")
    lines.append(f"= {1341 - float(total):.6f}`.")
    lines.append("")
    lines.append("`Stmt_PhiTable` (every entry is valid) and `Stmt_PhiData` (sorted, in `[0,1]`, the sum bound) are")
    lines.append("about this list.")
    lines.append("-/")
    lines.append("")
    lines.append("set_option linter.style.longLine false")
    lines.append("")
    lines.append("namespace ZetaWindow")
    lines.append("")
    CH = 450
    chunks = [P[i:i + CH] for i in range(0, len(P), CH)]
    names = []
    for ci, ch in enumerate(chunks):
        name = f"phiTable{ci}"
        names.append(name)
        lines.append(f"/-- Pieces {ci * CH} … {ci * CH + len(ch) - 1} of the φ-table (sorted by `x`). -/")
        lines.append(f"def {name} : List Piece := [")
        for i, (a, b, v) in enumerate(ch):
            sep = "," if i + 1 < len(ch) else "]"
            lines.append(f"  ⟨{a.numerator}, {a.denominator}, {b.numerator}, {b.denominator}, {v}⟩{sep}")
        lines.append("")
    lines.append("/-- The φ-table: all pieces of `(0, 1)` with `φ > 0`, sorted by `x`. -/")
    lines.append("def phiTable : List Piece := " + " ++ ".join(names))
    lines.append("")
    lines.append("end ZetaWindow")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true")
    ap.add_argument("--K", type=int, default=20)
    ap.add_argument("--crosscheck", default=None)
    args = ap.parse_args()
    T = terms()
    allp = pieces(T)
    P = [(a, b, v) for a, b, v in allp if v > 0]
    M = 60
    total = sum(weight(a, b, v, M, args.K) for a, b, v in P)
    print(f"breakpoint pieces: {len(allp)}, with phi > 0: {len(P)}, max phi {max(v for _, _, v in P)}")
    print(f"phiSumQ(K={args.K}) = {float(total):.10f};  1341 - phiSumQ = {1341 - float(total):.10f}")
    if args.crosscheck:
        import importlib.util
        spec = importlib.util.spec_from_file_location("vz", args.crosscheck)
        vz = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(vz)
        Tv = vz.compress(vz.terms_z04(ETA0, ETA, R))
        _, pv = vz.phi_integral(Tv, M)
        same = len(pv) == len(allp) and all(p1[0] == p2[0] and p1[1] == p2[1] and p1[2] == p2[2]
                                            for p1, p2 in zip(pv, allp))
        print("crosscheck against vz.py pieces:", "IDENTICAL" if same else "DIFFERENT")
    if args.write:
        import os
        here = os.path.dirname(os.path.abspath(__file__))
        path = os.path.join(here, "..", "Zeta2Lean", "Window", "PhiTable.lean")
        with open(path, "w", newline="\n", encoding="utf-8") as f:
            f.write(lean_file(P, args.K, total))
        print("wrote", os.path.normpath(path))


if __name__ == "__main__":
    main()
